require: rubocop-rails

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/ModuleFunction:
  Enabled: false

Layout/LineLength:
  Max: 100

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

